################################################################################
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
################################################################################
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
      day: friday
      time: "18:00"
      timezone: Europe/Zurich
    target-branch: main
    open-pull-requests-limit: 5
    pull-request-branch-name:
      separator: /
    labels:
      - type:dependencies

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: monthly
      day: friday
      time: "18:00"
      timezone: Europe/Zurich
    target-branch: main
    open-pull-requests-limit: 5
    pull-request-branch-name:
      separator: /
    labels:
      - type:dependencies
